Merged PR 256387: bugfix: null exception when logging plan ID
While helping a customer with [this issue](https://github.com/MicrosoftDocs/vsonline/issues/601), I found some 500s occuring because of a null exception on this line.
```
[NullReferenceException]: Object reference not set to an instance of an object.
--- Stack Trace ---
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VsSaaS.Services.CloudEnvironments.FrontEndWebApi.Controllers.EnvironmentsController.CreateAsync(CreateCloudEnvironmentBody createEnvironmentInput, IDiagnosticsLogger logger) in /source/src/FrontEnd/FrontEndWebApi/Src/FrontEndWebApi/Controllers/EnvironmentsController.cs:line 512
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

This looks like the more appropriate one to log.