Merged PR 258737: chore: RemoteInvocation Exception thrown during shutdown if resource isn't pr...
chore: RemoteInvocation Exception thrown during shutdown if resource isn't present.

Catching and handling remote invocation exception in windows codespaces is shutdown. In some cases, RemoteInvocationException is thrown instead of HttpResponseStatusException which is causing the shutdown to fail.

```

[RemoteInvocationException]: Server error
--- Stack Trace ---
Microsoft.VsSaaS.Services.CloudEnvironments.Common.RemoteInvocationException: Server error
   at Microsoft.VsSaaS.Services.CloudEnvironments.Common.HttpResponseMessageExtensions.ThrowServerJsonException(JObject details) in /source/src/Common/Src/Common/HttpResponseMessageExtensions.cs:line 82
   at Microsoft.VsSaaS.Services.CloudEnvironments.Common.HttpResponseMessageExtensions.ThrowIfFailedAsync(HttpResponseMessage response) in /source/src/Common/Src/Common/HttpResponseMessageExtensions.cs:line 55
   at Microsoft.VsSaaS.Services.CloudEnvironments.BackEndWebApiClient.HttpClientBase`1.SendRawAsync[TInput](HttpMethod method, String requestUri, TInput input, IDiagnosticsLogger logger) in /source/src/Common/Src/Common/HttpClientBase.cs:line 127
   at Microsoft.VsSaaS.Services.CloudEnvironments.BackEndWebApiClient.HttpClientBase`1.SendAsync[TInput,TResult](HttpMethod method, String requestUri, TInput input, IDiagnosticsLogger logger) in /source/src/Common/Src/Common/HttpClientBase.cs:line 69
   at Microsoft.VsSaaS.Services.CloudEnvironments.BackEndWebApiClient.ResourceBroker.HttpResourceBrokerClient.DeleteAsync(Guid environmentId, IEnumerable`1 resources, IDiagnosticsLogger logger) in /source/src/Codespaces/BackEndWebApiClient/Src/BackEndWebApiClient/ResourceBroker/HttpResourceBrokerClient.cs:line 117
   at Microsoft.VsSaaS.Services.CloudEnvironments.EnvironmentManager.Handlers.ShutdownEnvironmentContinuationHandler.DeleteComputeAsync(ShutdownEnvironmentContinuationInput operationInput, EnvironmentRecordRef record, IDiagnosticsLogger logger) in /source/src/Codespaces/EnvironmentManager/Src/EnvironmentManager/Handlers/ShutdownEnvironmentContinuationHandler.cs:line 156
   at Microsoft.VsSaaS.Services.CloudEnvironments.EnvironmentManager.Handlers.ShutdownEnvironmentContinuationHandler.RunOperationCoreAsync(ShutdownEnvironmentContinuationInput operationInput, EnvironmentRecordRef record, IDiagnosticsLogger logger) in /source/src/Codespaces/EnvironmentManager/Src/EnvironmentManager/Handlers/ShutdownEnvironmentContinuationHandler.cs:line 129
   at Microsoft.VsSaaS.Services.CloudEnvironments.EnvironmentManager.Handlers.BaseContinuationTaskMessageHandler`1.RunOperationAsync(TI input, EnvironmentRecordRef record, IDiagnosticsLogger logger) in /source/src/Codespaces/EnvironmentManager/Src/EnvironmentManager/Handlers/BaseContinuationTaskMessageHandler.cs:line 230
```

Since continuations are run in a different worker, need to corelate to find this issue.

To find the events in the last few hours when Anthony reproduced this issue.
```
DefaultEvent
| where CloudEnvironmentId == "4604d06a-4e9f-4635-810b-...