Merged PR 252285: bugfix: null check for record.value.storage
I believe this was introduced [here](https://devdiv.visualstudio.com/OnlineServices/_git/vsclk-core/commit/43527ae9099f4f09cf75ae0f5d80cd37b9efafeb?refName=refs%2Fheads%2Frelease%2F2020-06-02-hotfix&path=%2Fsrc%2FFrontEnd%2FEnvironmentManager%2FSrc%2FEnvironmentManager%2FHandlers%2FStartEnvironmentContinuationHandler.cs&_a=contents).

Not yet tested (not sure about the desired behavior here). This was causing issues resuming environments.

```
"ErrorException": NullReferenceException,
"ErrorMessage": Object reference not set to an instance of an object.,
"ErrorDetail": [NullReferenceException]: Object reference not set to an instance of an object.
--- Stack Trace ---
System.NullReferenceException: Object reference not set to an instance of an object.
 at Microsoft.VsSaaS.Services.CloudEnvironments.EnvironmentManager.StartEnvironmentContinuationHandler.<>c__DisplayClass38_0.<RunGetResourceAsync>b__0(StatusResponseBody x) in /source/src/FrontEnd/EnvironmentManager/Src/EnvironmentManager/Handlers/StartEnvironmentContinuationHandler.cs:line 299
 at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
 at Microsoft.VsSaaS.Services.CloudEnvironments.EnvironmentManager.StartEnvironmentContinuationHandler.RunGetResourceAsync(StartEnvironmentContinuationInput operationInput, EnvironmentRecordRef record, IDiagnosticsLogger logger) in /source/src/FrontEnd/EnvironmentManager/Src/EnvironmentManager/Handlers/StartEnvironmentContinuationHandler.cs:line 299
 at Microsoft.VsSaaS.Services.CloudEnvironments.EnvironmentManager.StartEnvironmentContinuationHandler.RunOperationCoreAsync(StartEnvironmentContinuationInput operationInput, EnvironmentRecordRef record, IDiagnosticsLogger logger) in /source/src/FrontEnd/EnvironmentManager/Src/EnvironmentManager/Handlers/StartEnvironmentContinuationHandler.cs:line 132
 at Microsoft.VsSaaS.Services.CloudEnvironments.EnvironmentManager.Handlers.BaseContinuationTaskMessageHandler`1.RunOperationAsync(TI input, EnvironmentRecordRef record, IDiagnosticsLogger logger) in /source/src/FrontEnd/EnvironmentManager/Src/EnvironmentManager/Handlers/BaseContinuationTaskMessageHandler.cs:line 230
```